fixing Epetra exe build
Compiling the Albany Epetra executable failed with:
error: 'Layouts' is not a member of 'Albany'
in multiple places in AMP. I included
"Albany_Layouts.hpp" to a few headers to fix this.

I'm not sure why this was compiling successfully
previously and what changed to make compilation
fail.