Update nightly test scripts to accommodate changes in Trilinos.
Switch to building/accessing shared libraries to overcome unresolved
symbol when linking:

/usr/lib/../lib64/libdl.a(dlsym.o): In function `dlsym':
undefined reference to `__dlopen'