Fix unresolved external in BlockDiscretization.
Address issue #605:
libalbanyLib.so: undefined reference to `Albany::BlockedDiscretization::writeSolutionMVToFile
(Thyra::MultiVectorBase<double> const&, double, bool)'
collect2: error: ld returned 1 exit status

(hopefully). I did not get this error when I tested, so it only appears on
some systems / environments; thus I was not able to verify that I fixed it. The nightly
tests should show if I did not, however.